drop table if exists USER;

create table USER
(
    USER_ID         INTEGER AUTO_INCREMENT,
    FIRSTNAME       VARCHAR(128) NOT NULL,
    LASTNAME        VARCHAR(128),
    USERNAME        VARCHAR(128) NOT NULL,
    PASSWORD        VARCHAR(128),
    CONFIRMPASSWORD VARCHAR(128),
    ROLES           VARCHAR(128),
    ENABLED BOOLEAN,
    OFF5 BOOLEAN,
    OFF10 BOOLEAN
);

drop table if exists CONFIRMATIONTOKEN;

create table CONFIRMATIONTOKEN(
      TOKENID INTEGER AUTO_INCREMENT,
      CREATEDDATE DATE NOT NULL,
      CONFIRMATIONTOKEN VARCHAR(128) NOT NULL,
      USER_ID INTEGER NOT NULL
);

drop table if exists PRODUCT;

create table PRODUCT (
    PRODUCTID INTEGER AUTO_INCREMENT,
    ORDERED INTEGER,
    PRICE INTEGER,
    AVAILABLE INTEGER
);

drop table if exists COUPONS;

create table COUPONS(
     COUPONID INTEGER AUTO_INCREMENT,
     NAME VARCHAR(128)
);

drop table if exists ORDER;

create table ORDER (
     ORDERID INTEGER AUTO_INCREMENT,
     USERID INTEGER,
     QUANTITY INTEGER,
     AMOUNT INTEGER,
     COUPON VARCHAR(128)
);

