drop table if exists USER;

create table USER
(
    USER_ID         INTEGER AUTO_INCREMENT,
    FIRSTNAME       VARCHAR(128) NOT NULL,
    LASTNAME        VARCHAR(128),
    USERNAME        VARCHAR(128) NOT NULL,
    PASSWORD        VARCHAR(128),
    CONFIRMPASSWORD VARCHAR(128),
    ROLES           VARCHAR(128),
    BALANCE INTEGER,
    ENABLED BOOLEAN

);

--For User Authentication
drop table if exists CONFIRMATIONTOKEN;

create table CONFIRMATIONTOKEN(
      TOKENID INTEGER AUTO_INCREMENT,
      CREATEDDATE DATE NOT NULL,
      CONFIRMATIONTOKEN VARCHAR(128) NOT NULL,
      USER_ID INTEGER NOT NULL
);

drop table if exists PRODUCT;

create table PRODUCT (
    PRODUCTID INTEGER AUTO_INCREMENT,
    ORDERED INTEGER,
    PRICE INTEGER,
    AVAILABLE INTEGER
);

drop table if exists COUPONS;

create table COUPONS(
     COUPONID INTEGER AUTO_INCREMENT,
     NAME VARCHAR(128)
);

drop table if exists ORDERDETAILS;

create table ORDERDETAILS (
     ORDERID INTEGER AUTO_INCREMENT,
     USERID INTEGER,
     QUANTITY INTEGER,
     AMOUNT INTEGER,
     CREATEDDATE DATE NOT NULL,
     COUPON VARCHAR(128)
);

drop table if exists USERCOUPONS;

create table USERCOUPONS(
    USERCOUPONSID INTEGER AUTO_INCREMENT,
    USERID INTEGER,
    COUPON VARCHAR(128),
    VALIDITY BOOLEAN
);

drop table if exists TRANSACTIONS;

create table TRANSACTIONS(
    TRANSACTIONID INTEGER AUTO_INCREMENT,
    USERID INTEGER,
    ORDERID INTEGER,
    AMOUNT INTEGER,
    CREATEDDATE DATE NOT NULL,
    STATUS VARCHAR(128),
    COUPON VARCHAR(128)
);


